In [2]:
import pandas as pd
import numpy as np

In [5]:
print(X.shape[0], X.shape[1])


50 4


In [3]:
np.random.seed(4)
# Step  1 Simulate data from known distribution

X = np.zeros((50,4))

# Prior probabilities (Y = 1), (Y = 2)
pi1 = 0.5
pi2 = 0.5
pi = np.array([pi1, pi2])

# Lets create some class labels acording to
# Priors probabilities, so we'll code class 1 as zero
# and clas 2 as 1

Y_train = np.random.choice([0,1], size = X.shape[0], p = [pi1, pi2])

# Lets generate the probability of getting ones for each feature
p = np.random.rand(X.shape[1])

for i in range(X.shape[0]):
  X[i] = np.random.binomial(1, p)


In [14]:
# Step 2 — Build the Bayes classifier using TRUE parameters:
# Since our futures are binary, each density function is just
# a Bernoully probability.
# Notice we already did calculate/define priors probability "pi1, pi2", now
# We should calculate the posterior probability, which is:
# If Xj = 1   f_kj(1) = P(Xj = 1| Y = k)
# If Xj = 0   f_kj(0) = 1 - P(Xj = 1| Y = k)
# p_hat(Xj = 1 | Y = k) = the proportion of all the X = 1
# in the k clas over the total number of observations in the kth class.


def bayes_classifier(x, X, Y_train, pi):
    K = len(pi)                 # number of classes
    p = X.shape[1]              # number of features

    numerators = np.zeros(K)    # stores pi_k * product of f_kj(x_j)

    for k in range(K):
        product_f_kp = 1

        for j in range(p):
            # estimate P(X_j = 1 | Y = k)
            p_hat = np.sum(X[Y_train == k, j]) / np.sum(Y_train == k)

            # Bernoulli likelihood
            if x[j] == 1:
                product_f_kp *= p_hat
            else:
                product_f_kp *= (1 - p_hat)

        numerators[k] = pi[k] * product_f_kp

    denominator = np.sum(numerators)
    posterior = numerators / denominator
    predicted_class = np.argmax(posterior)

    return posterior, predicted_class


In [20]:
# i. A vector of prior probabilities for each label in y
print("Prior probabilities:", pi)

# ii Class conditional probabilities P (xk = 1|Y= j),
# for k = 1, . . . , p and all labels j.
class_cond_probs = np.zeros((len(pi), X.shape[1]))

for k in range(len(pi)) :

  for j in range(X.shape[1]):
    class_cond_probs[k, j] = np.sum(X[Y_train == k, j]) / np.sum(Y_train == k)

print("Class conditional probabilities :")
print(class_cond_probs )

# iii. a vector of posterior probabilities P (Y= j|X= x) calculated from your algorithm.
posterior, predicted_class = bayes_classifier(X[0], X, Y_train, pi)
print('Posterior probabilities for first observation:')
print(posterior)

# iv. Predicted class for every observation
predicted_classe_for_each_obs = np.zeros(X.shape[0])

for i in range(X.shape[0]):
  results = bayes_classifier(X[i], X, Y_train, pi)
  predicted_classe_for_each_obs[i] = results[1]
print('Predicted class for every observation')
print(predicted_classe_for_each_obs)

# v. the misclassification rate (between 0 and 1) of your classifier
nbayes_error = np.mean(Y_train != predicted_classe_for_each_obs)
print("Naive Bayes Error:", nbayes_error)

Prior probabilities: [0.5 0.5]
Class conditional probabilities :
[[0.9047619  0.33333333 0.66666667 0.23809524]
 [0.82758621 0.4137931  0.62068966 0.27586207]]
Posterior probabilities for first observation:
[0.53479464 0.46520536]
Predicted class for every observation
[0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0.
 1. 0.]
Naive Bayes Error: 0.46


The Naive Bayes error rate is about 0.46, meaning the classifier correctly predicts about 54% of the observations.
This happens because the features X were generated independently of the class labels Y. Since X does not contain information about Y,
the classifier cannot effectively distinguish between the two classes, so its performance is close to random guessing (~50% accuracy).

If we instead generate X conditional on the class labels, so that
P(X_j = 1 | Y = 0) differs from P(X_j = 1 | Y = 1), then the error rate should change and the classifier would likely perform better.

In [28]:
np.random.seed(5)
# Step  1 Simulate data from known distribution

X_new= np.zeros((50,4))

# Prior probabilities (Y = 1), (Y = 2)
pi1 = np.random.rand()
pi2 = 1 - pi1
pi = np.array([pi1, pi2])
# Lets create some class labes acording to
# Priors probabilities, so we'll code class 1 as zero
# and clas 2 as 1

Y_train = np.random.choice([0,1], size = X_new.shape[0], p = [pi1, pi2])

# Lets generate the probability of getting ones for each feature
p = np.random.rand(X.shape[1])

for i in range(X.shape[0]):
  if Y_train[i] == 0:
    X_new[i] = np.random.binomial(1, p)
  else :
    X_new[i] = np.random.binomial(1, 1-p)


In [29]:
# i. A vector of prior probabilities for each label in y
print("Prior probabilities:", pi)

# ii Class conditional probabilities P (xk = 1|Y= j),
# for k = 1, . . . , p and all labels j.
class_cond_probs = np.zeros((len(pi), X_new.shape[1]))

for k in range(len(pi)) :

  for j in range(X_new.shape[1]):
    class_cond_probs[k, j] = np.sum(X_new[Y_train == k, j]) / np.sum(Y_train == k)

print("Class conditional probabilities :")
print(class_cond_probs )

# iii. a vector of posterior probabilities P (Y= j|X= x) calculated from your algorithm.
posterior, predicted_class = bayes_classifier(X_new[0], X_new, Y_train, pi)
print('Posterior probabilities for first observation:')
print(posterior)

# iv. Predicted class for every observation
predicted_classe_for_each_obs = np.zeros(X.shape[0])

for i in range(X_new.shape[0]):
  results = bayes_classifier(X_new[i], X_new, Y_train, pi)
  predicted_classe_for_each_obs[i] = results[1]
print('Predicted class for every observation')
print(predicted_classe_for_each_obs)

# v. the misclassification rate (between 0 and 1) of your classifier
nbayes_error = np.mean(Y_train != predicted_classe_for_each_obs)
print("Naive Bayes Error:", nbayes_error)

Prior probabilities: [0.22199317 0.77800683]
Class conditional probabilities :
[[0.41666667 0.         0.         0.08333333]
 [0.57894737 0.97368421 0.84210526 0.89473684]]
Posterior probabilities for first observation:
[0. 1.]
Predicted class for every observation
[1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 1. 1.]
Naive Bayes Error: 0.0


Now the new Naive Bayes Error = 0.0.

We will now proceed to generate new test data from the same distribution and see how well it does.

In [30]:
n_test = 30
X_test = np.zeros((n_test,4))
Y_test = np.random.choice([0,1], size = n_test, p = [pi1, pi2])

for i in range(n_test):
  if Y_test[i] == 0:
    X_test[i] = np.random.binomial(1, p)
  else:
    X_test[i] = np.random.binomial(1, 1-p)

In [25]:
posterior, pred = bayes_classifier(X_test[0], X_new, Y_train, pi)
print("Posterior probabilities:", posterior)
print("Predicted class:", pred)
print("True class:", Y_train[0])

Posterior probabilities: [0. 1.]
Predicted class: 1
True class: 1


In [26]:
y_pred_test = np.array([bayes_classifier(X_test[i], X_new, Y_train, pi)[1] for i in range(X_test.shape[0])])

test_error = np.mean(Y_test != y_pred_test)

print("Test Error:", test_error)

Test Error: 0.1


In [27]:
print(y_pred_test)
print(Y_test)

[1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0]
[1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 0]
